name: AVR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use avr-gcc docker image
        uses: docker://tobante/avr-gcc:9.2
        run: |
          make -C examples/avr/blink_interrupt
          cd examples/avr/blink_cmake
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake
          cmake --build build
          rm -rf build
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake
          cmake --build build
