name: AVR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: tobante/avr-gcc:9.2
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build atmega328p_uart project
        run: make -C examples/avr/atmega328p_uart

      - name: Build atmega328p_interrupt project
        run: |
          cd examples/avr/atmega328p_interrupt
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake
          cmake --build build
          rm -rf build
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake
          cmake --build build
